# Generated by Django 4.1.3 on 2022-11-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_imageprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
