# Generated by Django 4.0.6 on 2022-11-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprofile',
            old_name='UserImage',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='UserProfile',
            new_name='User',
        ),
    ]
